CREATE DATABASE PROJECT;
USE PROJECT;

DROP TABLE IF EXISTS USER;

DROP TABLE IF EXISTS USE_RECORD;

DROP TABLE IF EXISTS QUERY_RECORD;

DROP TABLE IF EXISTS DYNAMIC;

DROP TABLE IF EXISTS LIKE_TBL;

DROP TABLE IF EXISTS DONATE_TBL;

DROP TABLE IF EXISTS SUBSCRIBE_TBL;

DROP TABLE IF EXISTS QUERY_RECORD;

DROP TABLE IF EXISTS FEEDBACK;

CREATE TABLE USER (
        USERID INT NOT NULL AUTO_INCREMENT,
        NAME VARCHAR(10) NOT NULL,
        AGE INT NOT NULL,
        SEX CHAR(1) NOT NULL,
        UNAME VARCHAR(30) NOT NULL,
        PASSWORD VARCHAR(30) NOT NULL,
        AUT_NUM INT DEFAULT 0,
        PRIMARY KEY ( USERID )
);

CREATE TABLE USE_RECORD (
        RECORD_ID INT NOT NULL AUTO_INCREMENT,
        USERID INT NOT NULL,
        USE_TIME BIGINT NOT NULL,
        PIC_PATH VARCHAR(50) NOT NULL,
        PRIMARY KEY ( RECORD_ID )
);

CREATE TABLE QUERY_RECORD (
        RECORD_ID INT NOT NULL AUTO_INCREMENT,
        USERID INT NOT NULL,
        QUERYID INT NOT NULL,
        QUERYTIME BIGINT NOT NULL,
        PRIMARY KEY ( RECORD_ID )
);

CREATE TABLE DYNAMIC (
        DYNAMIC_ID INT NOT NULL AUTO_INCREMENT,
        USERID INT NOT NULL,
        PUBLISH_TIME BIGINT NOT NULL,
        DY_CONTENT VARCHAR(100) NOT NULL,
        RECORD_ID INT NOT NULL ,
        LIKE_COUNT INT NOT NULL DEFAULT 0,
        PRIMARY KEY ( DYNAMIC_ID )
);

CREATE TABLE COMMENT (
        COMMENT_ID INT NOT NULL AUTO_INCREMENT,
        USERID INT NOT NULL,
        PUBLISH_TIME BIGINT NOT NULL,
        COMMENT_CONTENT VARCHAR(100) NOT NULL,
        FORWARD_ID INT NOT NULL ,
        LIKE_COUNT INT NOT NULL DEFAULT 0,
        PRIMARY KEY ( COMMENT_ID )
);

CREATE TABLE LIKE_TBL (
        LIKE_ID INT NOT NULL AUTO_INCREMENT,
        DYNAMIC_ID INT NOT NULL,
        USERID INT NOT NULL,
        PRIMARY KEY ( LIKE_ID )
);
CREATE TABLE COMMENT_LIKE_TBL (
        LIKE_ID INT NOT NULL AUTO_INCREMENT,
        DYNAMIC_ID INT NOT NULL,
        USERID INT NOT NULL,
        PRIMARY KEY ( LIKE_ID )
);

CREATE TABLE DONATE_TBL (
        DONATE_ID INT NOT NULL AUTO_INCREMENT,
        USERID INT NOT NULL,
        COUNT INT NOT NULL,
        PRIMARY KEY ( DONATE_ID )
);

insert into user (name,age,sex,uname,password,aut_num) values ("Eileen",19,"F","EileenQueen","SweetCounter",2);